#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group veilid.
groups:
    - ubuntu: [root, sys]
    - veilid

# Add users to the system. Users are added after groups are added.
users:
    - default
    - name: veilid
      gecos: veilid
      shell: /bin/bash
      primary_group: veilid
      sudo: ALL=(ALL) NOPASSWD:ALL
      groups: users, admin
      lock_passwd: false
      ssh_authorized_keys:
        # put the value of the ssh-key you want to use here
        # EXAMPLE:
        # - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC56peg7LF9mmZzmk8KIm/HXGKMittedIuE6qi5UuPs0


# sets up veilid to run automatically
runcmd:
    - wget -O- https://packages.veilid.net/gpg/veilid-packages-key.public | sudo gpg --dearmor -o /usr/share/keyrings/veilid-packages-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/veilid-packages-keyring.gpg] https://packages.veilid.net/apt stable main" | sudo tee /etc/apt/sources.list.d/veilid.list 1>/dev/null
    - apt update
    # we need to explicitly update the iptables rules since the oracle VMs are configured to only accept tcp:22 and udp:123 by default
    - sudo iptables -I INPUT 5 -p tcp --dport 5150 -j ACCEPT
    - sudo iptables -I INPUT 5 -p udp --dport 5150 -j ACCEPT
    # lets also add the rules for ipv6
    - sudo ip6tables -I INPUT 5 -p tcp --dport 5150 -j ACCEPT
    - sudo ip6tables -I INPUT 5 -p udp --dport 5150 -j ACCEPT
    - sudo apt install veilid-server veilid-cli
    # we need this to make sure the node works behind the Oracle Cloud NAT, since we're not paying for a static IPv4 address
    - 'sudo sed -i ''/^ *network:/a \    detect_address_changes: true'' /etc/veilid-server/veilid-server.conf'
    - sudo systemctl enable --now veilid-server.service
    - sudo systemctl start veilid-server.service

# set up automatic updates just for these two packages every day at 5AM
write_files:
    - owner: root:root
      path: /etc/crontab
      content: |
          0 5 * * * root /usr/bin/apt update -y
          5 5 * * * root DEBIAN_FRONTEND=noninteractive /usr/bin/apt install --only-upgrade veilid-server veilid-cli -y
